Offence case 55555555 closure failed because java.net.ConnectException exception has been thrown - reconcile manually {"paymentID":1,"paidPenaltyAmount":40,"paidArrearsAmount":21,"payableArrearsAmount":24,"voluntaryArrearsPaid":12,"arrearsTo":"2016-08-30"}